### ISSUE TITLE
flag provided but not defined: -emitcheckpoints

### ISSUE THREAD

**Issue by JuManjey** [masa-finance/masa-node-v1.0#40]
after

`PRIVATE_CONFIG=ignore geth --identity LuckyNodeTech --datadir data --bootnodes enode://91a3c3d5e76b0acf05d9abddee959f1bcbc7c91537d2629288a9edd7a3df90acaa46ffba0e0e5d49a20598e0960ac458d76eb8fa92a1d64938c0a3a3d60f8be4@54.158.188.182:21000 --emitcheckpoints --istanbul.blockperiod 1 --mine --miner.threads 1 --syncmode full --verbosity 5 --networkid 190250 --rpc --rpccorsdomain "*" --rpcvhosts "*" --rpcaddr 127.0.0.1 --rpcport 8545 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --port 30300`

I get `flag provided but not defined: -emitcheckpoints`

Any idea?

**Comment by restevens402** [comment]
Some of the flags are specific to the GoQuorum geth client. It looks like this issue is a result of an Ethereum geth client being earlier in the path than the GoQuorum.  Make sure that you have built the GoQuorum according to instructions and add the geth executable in the build folder to the beginning of your path.  Hopefully, that solves it.

**Comment by JuManjey** [comment]
THX
